const properties = [
  {title:'Modern 5 Marla family home', city:'Johar Town, Lahore', price:'65,000', type:'House', beds:3, baths:3, size:'5 Marla', image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80', tag:'Featured'},
  {title:'Bright apartment near F-11 Markaz', city:'F-11, Islamabad', price:'95,000', type:'Apartment', beds:2, baths:2, size:'1,150 sq ft', image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80', tag:'New'},
  {title:'Peaceful upper portion with parking', city:'DHA Phase 6, Karachi', price:'72,000', type:'Upper Portion', beds:3, baths:3, size:'10 Marla', image:'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80', tag:'Featured'},
  {title:'Garden-facing executive flat', city:'Gulberg, Lahore', price:'115,000', type:'Flat', beds:3, baths:3, size:'1,600 sq ft', image:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80', tag:'New'}
];
let offset=0;
function renderCards(){const showing=[0,1,2].map(i=>properties[(i+offset)%properties.length]);document.querySelector('#propertyCards').innerHTML=showing.map((p,i)=>`<article class="card"><div class="card-img" style="background-image:url('${p.image}')"><span class="tag">${p.tag}</span><button class="heart" aria-label="Save ${p.title}">♡</button><span class="sample">Sample listing</span></div><div class="card-body"><div class="price">Rs. ${p.price} <small>/ month</small></div><h3>${p.title}</h3><p class="area">⌖ ${p.city} &nbsp;·&nbsp; ${p.type}</p><div class="features"><span><b>▣ ${p.beds}</b> Beds</span><span><b>▧ ${p.baths}</b> Baths</span><span><b>⌑</b> ${p.size}</span></div></div></article>`).join('');document.querySelectorAll('.heart').forEach(btn=>btn.addEventListener('click',()=>{btn.classList.toggle('liked');btn.textContent=btn.classList.contains('liked')?'♥':'♡';showToast(btn.classList.contains('liked')?'Saved to your favourites':'Removed from favourites')}));}
function showToast(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2700)}
renderCards();
document.querySelector('#next').addEventListener('click',()=>{offset=(offset+1)%properties.length;renderCards()});document.querySelector('#prev').addEventListener('click',()=>{offset=(offset+properties.length-1)%properties.length;renderCards()});
document.querySelector('#searchForm').addEventListener('submit',(e)=>{e.preventDefault();const city=document.querySelector('#locationInput').value||'Pakistan';const type=document.querySelector('#propertyType').value;const rent=document.querySelector('#rentRange').value;showToast(`Searching ${type.toLowerCase()} in ${city} · ${rent}`);document.querySelector('#listings').scrollIntoView({behavior:'smooth'})});
document.querySelectorAll('[data-toast]').forEach(el=>el.addEventListener('click',e=>{if(el.tagName==='A')e.preventDefault();showToast(el.dataset.toast)}));

