const STORAGE_KEY = 'gharrent-properties-v2';

const locationData = {
  Punjab: {Lahore:['Lahore City','Raiwind','Model Town','Shalimar','Cantonment','Ravi'],Rawalpindi:['Rawalpindi','Gujar Khan','Kahuta','Kallar Syedan','Kotli Sattian','Murree'],Faisalabad:['Faisalabad City','Jaranwala','Samundri','Tandlianwala','Chak Jhumra'],Gujranwala:['Gujranwala City','Kamoke','Nowshera Virkan','Wazirabad'],Multan:['Multan City','Shujabad','Jalalpur Pirwala'],Sialkot:['Sialkot','Daska','Pasrur','Sambrial'],Bahawalpur:['Bahawalpur City','Ahmadpur East','Hasilpur','Khairpur Tamewali','Yazman'],Sargodha:['Sargodha','Bhalwal','Bhera','Kot Momin','Sahiwal','Shahpur'],Sheikhupura:['Sheikhupura','Ferozewala','Muridke','Safdarabad','Sharaqpur'],Jhelum:['Jhelum','Dina','Pind Dadan Khan','Sohawa'],Gujrat:['Gujrat','Kharian','Sarai Alamgir'],Attock:['Attock','Fateh Jang','Hazro','Hasan Abdal','Jand','Pindi Gheb'],Chakwal:['Chakwal','Choa Saidan Shah','Kallar Kahar','Talagang'],Mianwali:['Mianwali','Esakhel','Piplan'],Khushab:['Khushab','Naushera','Quaidabad','Noorpur Thal'],Dera_Ghazi_Khan:['Dera Ghazi Khan','Kot Chutta','Taunsa'],Rahim_Yar_Khan:['Rahim Yar Khan','Khanpur','Liaquatpur','Sadiqabad'],Sahiwal:['Sahiwal','Chichawatni'],Okara:['Okara','Depalpur','Renala Khurd'],Kasur:['Kasur','Chunian','Kot Radha Kishan','Pattoki'],Nankana_Sahib:['Nankana Sahib','Shah Kot','Sangla Hill'],Narowal:['Narowal','Shakargarh','Zafarwal'],Hafizabad:['Hafizabad','Pindi Bhattian'],Mandi_Bahauddin:['Mandi Bahauddin','Malakwal','Phalia'],Pakpattan:['Pakpattan','Arifwala'],Lodhran:['Lodhran','Dunyapur','Kahror Pacca'],Vehari:['Vehari','Burewala','Mailsi'],Bahawalnagar:['Bahawalnagar','Chishtian','Fort Abbas','Haroonabad','Minchinabad'],Jhang:['Jhang','Shorkot','18-Hazari','Ahmadpur Sial']},
  Sindh: {Karachi:['Karachi Central','Karachi East','Karachi South','Karachi West','Korangi','Malir','Keamari'],Hyderabad:['Hyderabad City','Latifabad','Qasimabad','Hyderabad Rural'],Sukkur:['Sukkur City','New Sukkur','Rohri','Salehpat'],Larkana:['Larkana','Dokri','Ratodero','Bakrani'],Mirpur_Khas:['Mirpur Khas','Digri','Kot Ghulam Muhammad','Sindhri','Jhuddo'],Nawabshah:['Nawabshah','Daur','Sakrand','Qazi Ahmed'],Thatta:['Thatta','Mirpur Sakro','Keti Bandar','Ghorabari'],Badin:['Badin','Golarchi','Matli','Shaheed Fazil Rahu','Talhar'],Dadu:['Dadu','Johi','Khairpur Nathan Shah','Mehar'],Jacobabad:['Jacobabad','Garhi Khairo','Thul'],Khairpur:['Khairpur','Gambat','Kingri','Kot Diji','Nara','Sobhodero'],Sanghar:['Sanghar','Jam Nawaz Ali','Khipro','Shahdadpur','Sinjhoro','Tando Adam'],Tando_Muhammad_Khan:['Tando Muhammad Khan','Bulri Shah Karim','Tando Ghulam Hyder'],Tando_Allahyar:['Tando Allahyar','Jhando Mari','Chamber'],Umerkot:['Umerkot','Kunri','Pithoro','Samaro'],Ghotki:['Ghotki','Daharki','Khangarh','Mirpur Mathelo','Ubauro']},
  'Khyber Pakhtunkhwa': {Peshawar:['Peshawar City','Chamkani','Badaber','Hassan Khel','Mathra'],Abbottabad:['Abbottabad','Havelian','Lora'],Mardan:['Mardan','Katlang','Takht-i-Bahi'],Swat:['Babuzai','Barikot','Kabal','Khwazakhela','Matta','Mingora'],Nowshera:['Nowshera','Jehangira','Pabbi'],Kohat:['Kohat','Darra Adam Khel','Lachi'],Mansehra:['Mansehra','Baffa Pakhal','Balakot','Oghi'],Haripur:['Haripur','Ghazi','Khanpur'],Charsadda:['Charsadda','Shabqadar','Tangi'],Bannu:['Bannu','Domel','Kakki'],Dera_Ismail_Khan:['Dera Ismail Khan','Kulachi','Paharpur','Paroa'],Swabi:['Swabi','Lahor','Topi'],Dir_Upper:['Barawal','Dir','Kalkot','Wari'],Dir_Lower:['Adenzai','Balambat','Lal Qilla','Samar Bagh','Timergara'],Malakand:['Batkhela','Dargai'],Shangla:['Alpuri','Puran'],Buner:['Daggar','Gagra','Khudu Khel'],Karak:['Karak','Banda Daud Shah','Takht-e-Nasrati'],Hangu:['Hangu','Tall'],Lakki_Marwat:['Lakki Marwat','Sarai Gambila','Naurang'],Chitral:['Chitral','Mastuj'],Tank:['Tank','Jandola']},
  Balochistan: {Quetta:['Quetta City','Chaman','Nushki'],Gwadar:['Gwadar','Ormara','Pasni','Jiwani'],Khuzdar:['Khuzdar','Nal','Wadh','Zehri'],Turbat:['Turbat','Buleda','Dasht'],Sibi:['Sibi','Kutmandai'],Zhob:['Zhob','Sherani'],Chagai:['Dalbandin','Nok Kundi','Taftan'],Loralai:['Loralai','Duki','Mekhtar'],Lasbela:['Hub','Bela','Dureji'],Mastung:['Mastung','Dasht'],Killa_Saifullah:['Killa Saifullah','Muslim Bagh'],Pishin:['Pishin','Barshore','Hurramzai']},
  Islamabad: {Islamabad:['Islamabad']},
  Gilgit_Baltistan: {Gilgit:['Gilgit','Danyor','Jutial'],Skardu:['Skardu','Gamba Skardu','Roundu'],Hunza:['Aliabad','Gojal','Nagar'],Ghizer:['Gahkuch','Ishkoman','Punial']},
  'Azad Jammu & Kashmir': {Muzaffarabad:['Muzaffarabad','Naseerabad','Patikka'],Mirpur:['Mirpur','Dadyal','Chakswari'],Rawalakot:['Rawalakot','Hajira','Thorar'],Kotli:['Kotli','Charhoi','Fatehpur Thakiala']}
};
const provinceNames=Object.keys(locationData);
const cityRecords=provinceNames.flatMap(province=>Object.entries(locationData[province]).map(([city,tehsils])=>({province,city:city.replaceAll('_',' '),tehsils})));
const demoProperties=[
 {title:'Modern 5 Marla family home',city:'Johar Town, Lahore',rawCity:'Lahore',price:'65,000',type:'House',beds:3,baths:3,size:'5 Marla',image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',tag:'Featured',sample:true},
 {title:'Bright apartment near F-11 Markaz',city:'F-11, Islamabad',rawCity:'Islamabad',price:'95,000',type:'Apartment',beds:2,baths:2,size:'1,150 sq ft',image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80',tag:'New',sample:true},
 {title:'Peaceful upper portion with parking',city:'DHA Phase 6, Karachi',rawCity:'Karachi',price:'72,000',type:'Portion',beds:3,baths:3,size:'10 Marla',image:'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80',tag:'Featured',sample:true},
 {title:'Garden-facing executive flat',city:'Gulberg, Lahore',rawCity:'Lahore',price:'115,000',type:'Apartment',beds:3,baths:3,size:'1,600 sq ft',image:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80',tag:'New',sample:true}
];
let userProperties=loadUserProperties(),offset=0,activeResults=[...demoProperties,...userProperties];
function loadUserProperties(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}}
function saveUserProperties(){localStorage.setItem(STORAGE_KEY,JSON.stringify(userProperties))}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(v){return Number(String(v).replace(/[^0-9]/g,'')||0).toLocaleString('en-PK')}
function showToast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2700)}
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}
function renderCards(){const c=document.querySelector('#propertyCards');if(!activeResults.length){c.innerHTML='<div class="empty-state">No properties match these filters yet. Try another city or post the first property.</div>';return}const showing=[0,1,2].map(i=>activeResults[(i+offset)%activeResults.length]).filter(Boolean);c.innerHTML=showing.map(p=>`<article class="card"><div class="card-img" style="background-image:url('${escapeHtml(p.image||demoProperties[0].image)}')"><span class="tag">${escapeHtml(p.tag||'New')}</span><button class="heart" type="button" aria-label="Save ${escapeHtml(p.title)}">♡</button>${p.sample?'<span class="sample">Demo listing</span>':''}</div><div class="card-body"><div class="price">Rs. ${escapeHtml(money(p.price))} <small>/ month</small></div><h3>${escapeHtml(p.title)}</h3><p class="area">⌖ ${escapeHtml(p.city)} &nbsp;·&nbsp; ${escapeHtml(p.type)}</p><div class="features"><span><b>▣ ${escapeHtml(p.beds)}</b> Beds</span><span><b>▧ ${escapeHtml(p.baths)}</b> Baths</span><span><b>⌑</b> ${escapeHtml(p.size)}</span></div>${p.description?`<p class="listing-description">${escapeHtml(p.description)}</p>`:''}${p.phone?`<button type="button" class="contact-owner" data-phone="${escapeHtml(p.phone)}">Contact owner</button>`:''}</div></article>`).join('');document.querySelectorAll('.heart').forEach(b=>b.addEventListener('click',()=>{b.classList.toggle('liked');b.textContent=b.classList.contains('liked')?'♥':'♡';showToast(b.classList.contains('liked')?'Saved to your favourites':'Removed from favourites')}));document.querySelectorAll('.contact-owner').forEach(b=>b.addEventListener('click',()=>showToast(`Owner contact: ${b.dataset.phone}`)))}
function setResults(results,title,meta){activeResults=results;offset=0;document.querySelector('#listingTitle').textContent=title;document.querySelector('#listingMeta').textContent=meta;renderCards();scrollToId('listings')}
function search(){const city=document.querySelector('#locationInput').value.trim(),type=document.querySelector('#propertyType').value,rent=document.querySelector('#rentRange').value,q=city.toLowerCase();const results=[...demoProperties,...userProperties].filter(p=>{const loc=(p.city+' '+(p.rawCity||'')).toLowerCase(),t=type==='All homes'||p.type.toLowerCase()===type.toLowerCase(),l=!q||loc.includes(q),price=Number(String(p.price).replace(/[^0-9]/g,''))||0,r=rent==='Any budget'||(rent==='Under Rs. 50,000'&&price<50000)||(rent==='Rs. 50k – 100k'&&price>=50000&&price<=100000)||(rent==='Rs. 100k – 200k'&&price>100000&&price<=200000)||(rent==='Above Rs. 200k'&&price>200000);return t&&l&&r});setResults(results,results.length?`Homes in ${city||'Pakistan'}`:'No matching homes',`${results.length} listing${results.length===1?'':'s'} found · ${type} · ${rent}`)}
function fillCitySelect(){const s=document.querySelector('#postCity');s.innerHTML='<option value="">Select city</option>'+cityRecords.sort((a,b)=>a.city.localeCompare(b.city)).map(r=>`<option value="${escapeHtml(r.city)}" data-province="${escapeHtml(r.province)}">${escapeHtml(r.city)} — ${escapeHtml(r.province)}</option>`).join('')}
function updateTehsilSelect(city){const s=document.querySelector('#postTehsil'),r=cityRecords.find(x=>x.city===city);s.disabled=!r;s.innerHTML=r?'<option value="">Select tehsil</option>'+r.tehsils.map(t=>`<option>${escapeHtml(t)}</option>`).join(''):'<option value="">Select city first</option>'}
function openDialog(id){const d=document.getElementById(id);if(!d.open)d.showModal()}function closeDialog(id){document.getElementById(id)?.close()}
function openPost(){document.querySelector('#postForm').reset();updateTehsilSelect('');openDialog('postDialog')}
function openCities(){renderCityList('');openDialog('citiesDialog')}
function renderCityList(filter){const q=filter.toLowerCase().trim(),groups=provinceNames.map(province=>({province,cities:Object.entries(locationData[province]).map(([city,tehsils])=>({city:city.replaceAll('_',' '),tehsils})).filter(x=>!q||x.city.toLowerCase().includes(q)||x.tehsils.some(t=>t.toLowerCase().includes(q)))})).filter(g=>g.cities.length);document.querySelector('#cityList').innerHTML=groups.map(g=>`<section><h3>${escapeHtml(g.province)}</h3>${g.cities.map(c=>`<button type="button" data-browser-city="${escapeHtml(c.city)}"><b>${escapeHtml(c.city)}</b><span>${escapeHtml(c.tehsils.join(' · '))}</span></button>`).join('')}</section>`).join('')||'<p class="empty-state">No city or tehsil found.</p>';document.querySelectorAll('[data-browser-city]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#locationInput').value=b.dataset.browserCity;closeDialog('citiesDialog');search()}))}
function openInfo(title,text,content=''){document.querySelector('#infoTitle').textContent=title;document.querySelector('#infoText').textContent=text;document.querySelector('#infoContent').innerHTML=content;openDialog('infoDialog')}
function handleAction(a){switch(a){case'open-post':openPost();break;case'close-post':closeDialog('postDialog');break;case'open-cities':openCities();break;case'close-cities':closeDialog('citiesDialog');break;case'close-info':closeDialog('infoDialog');break;case'scroll-browse':scrollToId('browse');break;case'scroll-listings':scrollToId('listings');break;case'open-safety':openInfo('Safety centre','Practical checks for a safer rental experience.','<ul><li>Never send advance payment before verifying the property and owner.</li><li>Meet at the property and compare the listing details with what you see.</li><li>Report information that looks suspicious or misleading.</li></ul>');break;case'open-help':openInfo('Help centre','Find or post a home without signing in.','<p>Use search filters, browse by city and tehsil, or use <strong>Post property</strong> to save a rental listing on this device.</p>');break;case'open-contact':openInfo('Contact GharRent','Support tools are being built into the marketplace.','<p>For now, use the listing and reporting tools on this page. A server-backed support inbox can be connected later.</p>');break;case'open-report':openInfo('Report a problem','Tell us what looks wrong.','<p>Include the property title, city and the issue you noticed so it can be reviewed.</p>');break;case'open-saved':showToast('Saved homes are stored on this device when you tap the heart icon.');break;case'open-account':showToast('No sign-in is required. Browse and post locally without an account.');break}}
fillCitySelect();renderCards();
document.querySelector('#next').addEventListener('click',()=>{offset=(offset+1)%Math.max(activeResults.length,1);renderCards()});document.querySelector('#prev').addEventListener('click',()=>{offset=(offset+Math.max(activeResults.length,1)-1)%Math.max(activeResults.length,1);renderCards()});document.querySelector('#searchForm').addEventListener('submit',e=>{e.preventDefault();search()});document.querySelector('#postCity').addEventListener('change',e=>updateTehsilSelect(e.target.value));document.querySelector('#cityFilter').addEventListener('input',e=>renderCityList(e.target.value));document.querySelectorAll('[data-action]').forEach(e=>e.addEventListener('click',()=>handleAction(e.dataset.action)));document.querySelectorAll('[data-city]').forEach(e=>e.addEventListener('click',()=>{document.querySelector('#locationInput').value=e.dataset.city;search()}));document.querySelectorAll('[data-type]').forEach(e=>e.addEventListener('click',()=>{document.querySelector('#propertyType').value=e.dataset.type;search()}));document.querySelectorAll('[data-province]').forEach(e=>e.addEventListener('click',()=>openInfo(e.dataset.province,`Cities and tehsils in ${e.dataset.province}`,'<p>Open <strong>View all cities</strong> to search and select any city or tehsil.</p>')));document.querySelectorAll('[data-search-tab]').forEach(e=>e.addEventListener('click',()=>{document.querySelectorAll('[data-search-tab]').forEach(x=>x.classList.remove('active'));e.classList.add('active');if(e.dataset.searchTab==='commercial')showToast('Commercial mode is not enabled yet — GharRent is focused on homes for rent.')}));
document.querySelector('#postForm').addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries()),property={...data,rawCity:data.city,city:`${data.area}, ${data.city}`,price:money(data.price),tag:'New',sample:false,image:demoProperties[0].image};userProperties.unshift(property);saveUserProperties();closeDialog('postDialog');setResults([...userProperties,...demoProperties],'Your latest properties',`${userProperties.length} propert${userProperties.length===1?'y':'ies'} saved on this device`);showToast('Property posted successfully on this device.')});document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
