/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountDeletionRouteImport } from './routes/account-deletion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DotwellKnownAssetlinksDotjsonRouteImport } from './routes/[.]well-known/assetlinks[.]json'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountListingsRouteImport } from './routes/account/listings'
import { Route as AccountSavedRouteImport } from './routes/account/saved'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminListingsRouteImport } from './routes/admin/listings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as PostIndexRouteImport } from './routes/post/index'
import { Route as PostIdRouteImport } from './routes/post/$id'
import { Route as PropertySlugRouteImport } from './routes/property/$slug'
import { Route as RentIndexRouteImport } from './routes/rent/index'
import { Route as SaleIndexRouteImport } from './routes/sale/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiImagesIdRouteImport } from './routes/api/images/$id'
import { Route as RentProvinceIndexRouteImport } from './routes/rent/$province/index'
import { Route as SaleProvinceIndexRouteImport } from './routes/sale/$province/index'
import { Route as RentProvinceDistrictIndexRouteImport } from './routes/rent/$province/$district/index'
import { Route as RentProvinceDistrictTypeRouteImport } from './routes/rent/$province/$district/$type'
import { Route as SaleProvinceDistrictIndexRouteImport } from './routes/sale/$province/$district/index'
import { Route as SaleProvinceDistrictTypeRouteImport } from './routes/sale/$province/$district/$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletionRoute = AccountDeletionRouteImport.update({
  id: '/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAssetlinksDotjsonRoute =
  DotwellKnownAssetlinksDotjsonRouteImport.update({
    id: '/.well-known/assetlinks.json',
    path: '/.well-known/assetlinks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountListingsRoute = AccountListingsRouteImport.update({
  id: '/account/listings',
  path: '/account/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSavedRoute = AccountSavedRouteImport.update({
  id: '/account/saved',
  path: '/account/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/admin/listings',
  path: '/admin/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIndexRoute = PostIndexRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertySlugRoute = PropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RentIndexRoute = RentIndexRouteImport.update({
  id: '/rent/',
  path: '/rent/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleIndexRoute = SaleIndexRouteImport.update({
  id: '/sale/',
  path: '/sale/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesIdRoute = ApiImagesIdRouteImport.update({
  id: '/api/images/$id',
  path: '/api/images/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RentProvinceIndexRoute = RentProvinceIndexRouteImport.update({
  id: '/rent/$province/',
  path: '/rent/$province/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleProvinceIndexRoute = SaleProvinceIndexRouteImport.update({
  id: '/sale/$province/',
  path: '/sale/$province/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentProvinceDistrictIndexRoute =
  RentProvinceDistrictIndexRouteImport.update({
    id: '/rent/$province/$district/',
    path: '/rent/$province/$district/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RentProvinceDistrictTypeRoute =
  RentProvinceDistrictTypeRouteImport.update({
    id: '/rent/$province/$district/$type',
    path: '/rent/$province/$district/$type',
    getParentRoute: () => rootRouteImport,
  } as any)
const SaleProvinceDistrictIndexRoute =
  SaleProvinceDistrictIndexRouteImport.update({
    id: '/sale/$province/$district/',
    path: '/sale/$province/$district/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SaleProvinceDistrictTypeRoute =
  SaleProvinceDistrictTypeRouteImport.update({
    id: '/sale/$province/$district/$type',
    path: '/sale/$province/$district/$type',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/account/listings': typeof AccountListingsRoute
  '/account/saved': typeof AccountSavedRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/post/$id': typeof PostIdRoute
  '/property/$slug': typeof PropertySlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/post/': typeof PostIndexRoute
  '/rent/': typeof RentIndexRoute
  '/sale/': typeof SaleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$id': typeof ApiImagesIdRoute
  '/rent/$province/': typeof RentProvinceIndexRoute
  '/sale/$province/': typeof SaleProvinceIndexRoute
  '/rent/$province/$district/$type': typeof RentProvinceDistrictTypeRoute
  '/sale/$province/$district/$type': typeof SaleProvinceDistrictTypeRoute
  '/rent/$province/$district/': typeof RentProvinceDistrictIndexRoute
  '/sale/$province/$district/': typeof SaleProvinceDistrictIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/account/listings': typeof AccountListingsRoute
  '/account/saved': typeof AccountSavedRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/post/$id': typeof PostIdRoute
  '/property/$slug': typeof PropertySlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/post': typeof PostIndexRoute
  '/rent': typeof RentIndexRoute
  '/sale': typeof SaleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$id': typeof ApiImagesIdRoute
  '/rent/$province': typeof RentProvinceIndexRoute
  '/sale/$province': typeof SaleProvinceIndexRoute
  '/rent/$province/$district/$type': typeof RentProvinceDistrictTypeRoute
  '/sale/$province/$district/$type': typeof SaleProvinceDistrictTypeRoute
  '/rent/$province/$district': typeof RentProvinceDistrictIndexRoute
  '/sale/$province/$district': typeof SaleProvinceDistrictIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/account/listings': typeof AccountListingsRoute
  '/account/saved': typeof AccountSavedRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/post/$id': typeof PostIdRoute
  '/property/$slug': typeof PropertySlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/post/': typeof PostIndexRoute
  '/rent/': typeof RentIndexRoute
  '/sale/': typeof SaleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$id': typeof ApiImagesIdRoute
  '/rent/$province/': typeof RentProvinceIndexRoute
  '/sale/$province/': typeof SaleProvinceIndexRoute
  '/rent/$province/$district/$type': typeof RentProvinceDistrictTypeRoute
  '/sale/$province/$district/$type': typeof SaleProvinceDistrictTypeRoute
  '/rent/$province/$district/': typeof RentProvinceDistrictIndexRoute
  '/sale/$province/$district/': typeof SaleProvinceDistrictIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deletion'
    | '/contact'
    | '/disclaimer'
    | '/locations'
    | '/login'
    | '/privacy'
    | '/report'
    | '/robots.txt'
    | '/safety'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/assetlinks.json'
    | '/account/listings'
    | '/account/saved'
    | '/admin/listings'
    | '/admin/reports'
    | '/admin/users'
    | '/post/$id'
    | '/property/$slug'
    | '/account/'
    | '/admin/'
    | '/post/'
    | '/rent/'
    | '/sale/'
    | '/api/auth/$'
    | '/api/images/$id'
    | '/rent/$province/'
    | '/sale/$province/'
    | '/rent/$province/$district/$type'
    | '/sale/$province/$district/$type'
    | '/rent/$province/$district/'
    | '/sale/$province/$district/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deletion'
    | '/contact'
    | '/disclaimer'
    | '/locations'
    | '/login'
    | '/privacy'
    | '/report'
    | '/robots.txt'
    | '/safety'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/assetlinks.json'
    | '/account/listings'
    | '/account/saved'
    | '/admin/listings'
    | '/admin/reports'
    | '/admin/users'
    | '/post/$id'
    | '/property/$slug'
    | '/account'
    | '/admin'
    | '/post'
    | '/rent'
    | '/sale'
    | '/api/auth/$'
    | '/api/images/$id'
    | '/rent/$province'
    | '/sale/$province'
    | '/rent/$province/$district/$type'
    | '/sale/$province/$district/$type'
    | '/rent/$province/$district'
    | '/sale/$province/$district'
  id:
    | '__root__'
    | '/'
    | '/account-deletion'
    | '/contact'
    | '/disclaimer'
    | '/locations'
    | '/login'
    | '/privacy'
    | '/report'
    | '/robots.txt'
    | '/safety'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/assetlinks.json'
    | '/account/listings'
    | '/account/saved'
    | '/admin/listings'
    | '/admin/reports'
    | '/admin/users'
    | '/post/$id'
    | '/property/$slug'
    | '/account/'
    | '/admin/'
    | '/post/'
    | '/rent/'
    | '/sale/'
    | '/api/auth/$'
    | '/api/images/$id'
    | '/rent/$province/'
    | '/sale/$province/'
    | '/rent/$province/$district/$type'
    | '/sale/$province/$district/$type'
    | '/rent/$province/$district/'
    | '/sale/$province/$district/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountDeletionRoute: typeof AccountDeletionRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SafetyRoute: typeof SafetyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  DotwellKnownAssetlinksDotjsonRoute: typeof DotwellKnownAssetlinksDotjsonRoute
  AccountListingsRoute: typeof AccountListingsRoute
  AccountSavedRoute: typeof AccountSavedRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  PostIdRoute: typeof PostIdRoute
  PropertySlugRoute: typeof PropertySlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PostIndexRoute: typeof PostIndexRoute
  RentIndexRoute: typeof RentIndexRoute
  SaleIndexRoute: typeof SaleIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiImagesIdRoute: typeof ApiImagesIdRoute
  RentProvinceIndexRoute: typeof RentProvinceIndexRoute
  SaleProvinceIndexRoute: typeof SaleProvinceIndexRoute
  RentProvinceDistrictTypeRoute: typeof RentProvinceDistrictTypeRoute
  SaleProvinceDistrictTypeRoute: typeof SaleProvinceDistrictTypeRoute
  RentProvinceDistrictIndexRoute: typeof RentProvinceDistrictIndexRoute
  SaleProvinceDistrictIndexRoute: typeof SaleProvinceDistrictIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deletion': {
      id: '/account-deletion'
      path: '/account-deletion'
      fullPath: '/account-deletion'
      preLoaderRoute: typeof AccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/assetlinks.json': {
      id: '/.well-known/assetlinks.json'
      path: '/.well-known/assetlinks.json'
      fullPath: '/.well-known/assetlinks.json'
      preLoaderRoute: typeof DotwellKnownAssetlinksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/listings': {
      id: '/account/listings'
      path: '/account/listings'
      fullPath: '/account/listings'
      preLoaderRoute: typeof AccountListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/saved': {
      id: '/account/saved'
      path: '/account/saved'
      fullPath: '/account/saved'
      preLoaderRoute: typeof AccountSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/admin/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/': {
      id: '/post/'
      path: '/post'
      fullPath: '/post/'
      preLoaderRoute: typeof PostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$slug': {
      id: '/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof PropertySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/': {
      id: '/rent/'
      path: '/rent'
      fullPath: '/rent/'
      preLoaderRoute: typeof RentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale/': {
      id: '/sale/'
      path: '/sale'
      fullPath: '/sale/'
      preLoaderRoute: typeof SaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$id': {
      id: '/api/images/$id'
      path: '/api/images/$id'
      fullPath: '/api/images/$id'
      preLoaderRoute: typeof ApiImagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/$province/': {
      id: '/rent/$province/'
      path: '/rent/$province'
      fullPath: '/rent/$province/'
      preLoaderRoute: typeof RentProvinceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale/$province/': {
      id: '/sale/$province/'
      path: '/sale/$province'
      fullPath: '/sale/$province/'
      preLoaderRoute: typeof SaleProvinceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/$province/$district/': {
      id: '/rent/$province/$district/'
      path: '/rent/$province/$district'
      fullPath: '/rent/$province/$district/'
      preLoaderRoute: typeof RentProvinceDistrictIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/$province/$district/$type': {
      id: '/rent/$province/$district/$type'
      path: '/rent/$province/$district/$type'
      fullPath: '/rent/$province/$district/$type'
      preLoaderRoute: typeof RentProvinceDistrictTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale/$province/$district/': {
      id: '/sale/$province/$district/'
      path: '/sale/$province/$district'
      fullPath: '/sale/$province/$district/'
      preLoaderRoute: typeof SaleProvinceDistrictIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale/$province/$district/$type': {
      id: '/sale/$province/$district/$type'
      path: '/sale/$province/$district/$type'
      fullPath: '/sale/$province/$district/$type'
      preLoaderRoute: typeof SaleProvinceDistrictTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountDeletionRoute: AccountDeletionRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SafetyRoute: SafetyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  DotwellKnownAssetlinksDotjsonRoute: DotwellKnownAssetlinksDotjsonRoute,
  AccountListingsRoute: AccountListingsRoute,
  AccountSavedRoute: AccountSavedRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  PostIdRoute: PostIdRoute,
  PropertySlugRoute: PropertySlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  PostIndexRoute: PostIndexRoute,
  RentIndexRoute: RentIndexRoute,
  SaleIndexRoute: SaleIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiImagesIdRoute: ApiImagesIdRoute,
  RentProvinceIndexRoute: RentProvinceIndexRoute,
  SaleProvinceIndexRoute: SaleProvinceIndexRoute,
  RentProvinceDistrictTypeRoute: RentProvinceDistrictTypeRoute,
  SaleProvinceDistrictTypeRoute: SaleProvinceDistrictTypeRoute,
  RentProvinceDistrictIndexRoute: RentProvinceDistrictIndexRoute,
  SaleProvinceDistrictIndexRoute: SaleProvinceDistrictIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
